export { AudioEngine, getAudioEngine, __resetAudioEngineSingleton } from './audioEngine';
export { SfxContext, SfxProvider, useSfx } from './SfxContext';
export type { SfxContextValue, SfxProviderProps } from './SfxContext';
export { useClickSfx, useHoverSfx } from './hooks';
export type { HoverSfxTarget, UseHoverSfxOptions } from './hooks';
export { useAudioEngine } from './useAudioEngine';
export type { UseAudioEngineReturn } from './useAudioEngine';
export type { UseAudioEngineOptions } from './useAudioEngine.types';
export type { SfxEvent, SfxEntry } from './config';
export { SFX_CONFIG, DUCK_VOLUME, DUCK_RAMP_MS, DEFAULT_SOUND_BASE_URL } from './config';
